name: Botzin dos cria

on:
  workflow_dispatch:  # Allows manual runs
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the Python script
        env:
          BOT_KEY: ${{ secrets.BOT_KEY }}
          CHAT_KEY: ${{ secrets.CHAT_KEY }}
          GROUP_KEY: ${{ secrets.GROUP_KEY }}
        run: |
          for i in {1..10}
          do
            python script.py
            sleep 30  # Wait for 30 seconds between runs
          done
